# 1. Load up Excel file

In [59]:
import pandas as pd

pointfinder_file = '../../pointfinder.xlsx'

pointfinder_excel = pd.ExcelFile(pointfinder_file)
sheets_df_map_orig = {n: pd.read_excel(pointfinder_excel, sheet_name=n, header=None) for n in pointfinder_excel.sheet_names}
sheets_df_map_orig.keys()

dict_keys(['Salmonella', 'Shigella E. coli', 'Campylobacter', 'NCBI AMRfinder'])

# 2. Add organism names/column names

In [60]:
sheets_df_map = {
    'salmonella': sheets_df_map_orig['Salmonella'],
    'escherichia_coli': sheets_df_map_orig['Shigella E. coli'],
    'campylobacter': sheets_df_map_orig['Campylobacter'],
}

sheets_df_map = {n: sheets_df_map[n].rename({0: 'gene_mutation', 1: 'Drug'},
                                        axis='columns') for n in sheets_df_map}
for n in sheets_df_map:
    sheets_df_map[n].insert(0, 'Organism', n)
    
sheets_df_map['salmonella'].head(3)

     Organism gene_mutation      Drug
0  salmonella      pmrA(15)  colistin
1  salmonella      pmrA(53)  colistin
2  salmonella      pmrA(81)  colistin

In [61]:
pointfinder_df = pd.concat([sheets_df_map['salmonella'],
                  sheets_df_map['escherichia_coli'],
                  sheets_df_map['campylobacter']
]).reset_index(drop=True)

pointfinder_df.head(3)

     Organism gene_mutation      Drug    2
0  salmonella      pmrA(15)  colistin  NaN
1  salmonella      pmrA(53)  colistin  NaN
2  salmonella      pmrA(81)  colistin  NaN

# 3. Fix up columns

In [ ]:
import re

def split_gene_position(row):
    gene_mutation = row['gene_mutation']

    # ampCprom case: ampCprom-pos -> the negative is part of the pos (ex: ampCprom-42)
    if gene_mutation.lower().startswith("ampcprom"):
      gene = "ampCprom"
      pos = int(gene_mutation.split("ampCprom")[1])

    # Brackets case: gene(pos) (ex: 16S_rrsH(1192))
    elif "(" in gene_mutation and ")" in gene_mutation and gene_mutation.index("(") < gene_mutation.index(")"):
      left_bracket_pos = gene_mutation.index("(")
      right_bracket_pos = gene_mutation.index(")")
      gene = gene_mutation[:left_bracket_pos]
      pos = int(gene_mutation[left_bracket_pos + 1:right_bracket_pos])

    # From->To case: gene_FposT (ex: parC_A56T)
    elif "_" in gene_mutation:
      tokens = gene_mutation.split("_")
      gene = tokens[0]
      pos = int(re.search(r"-?\d+", tokens[1]).group())
    
    else:
       print("Could not process: " + str(gene_mutation))

    result = [gene, pos]
    return pd.Series(result)


pointfinder_df_reduced = pointfinder_df.copy()
pointfinder_df_reduced[['Gene', 'Codon Pos.']] = pointfinder_df_reduced.apply(split_gene_position, 1)

pointfinder_df_reduced = pointfinder_df_reduced[['Organism', 'Gene', 'Codon Pos.', 'Drug']]
pointfinder_df_reduced['Gene'] = pointfinder_df_reduced['Gene'].str.replace('ampCprom', 'ampC_promoter')
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.strip()
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.lower()
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.replace('i/r', 'I/R')
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.replace(' ', ',')
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.replace(',acid', ' acid')
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.replace(',I/R', ' I/R')
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].str.replace('inI/R', 'in I/R')
pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].replace('none', 'None')
# pointfinder_df_reduced['Drug'] = pointfinder_df_reduced['Drug'].replace('None', pd.NA)

pointfinder_df_reduced.drop_duplicates()
pointfinder_df_reduced

          Organism  Gene  Codon Pos.                          Drug
0       salmonella  pmrA          15                      colistin
1       salmonella  pmrA          53                      colistin
2       salmonella  pmrA          81                      colistin
3       salmonella  pmrB          14                      colistin
4       salmonella  pmrB          22                      colistin
..             ...   ...         ...                           ...
173  campylobacter  gyrA          86  ciprofloxacin,nalidixic acid
174  campylobacter  rplV          86                  erythromycin
175  campylobacter  rpsL          43                  streptomycin
176  campylobacter  gyrA         104  ciprofloxacin,nalidixic acid
177  campylobacter  rplV          88                  erythromycin

[178 rows x 4 columns]

# 4. Save pointfinder resitance table

In [63]:
pointfinder_df_reduced.to_csv('../../staramr/databases/resistance/data/ARG_drug_key_pointfinder.tsv', sep='\t', index=False)